### ISSUE TITLE
[DEPRECATION] MovieTexture is deprecated

### ISSUE THREAD

**Issue by louisgv** [DanGiaime/IGME119-2DPlatformer#1]
FYI, MovieTexture is deprecated, please update the animatic player to use Video Player instead.

Related: https://github.com/DanGiaime/IGME119-2DPlatformer/blob/master/IGME119-2DPlatformer/Assets/Scripts/VideoController.cs#L6

**Comment by roxworks** [comment]
Fixed. Thanks for pointing that out.
