### ISSUE TITLE
Enemies do not attack by themselves

### ISSUE THREAD

**Issue by etclark** [DanGiaime/IGME119-2DPlatformer#12]
I don't know when the enemy attack animation is supposed to play because the enemies do not ever attack. They shoot their bullets but never change from the walking animation. In fact, it appears that the Enemy_Controller animator controller does not have any animations attached to it.

**Comment by etclark** [comment]
Please fix enemy animation. We have no reason to create an idle, or attack animation for them since they never idle or attack. Currently their default is to always walk to the left. Feel free to correct me if I'm wrong.

**Comment by roxworks** [comment]
My apologies, somehow the animations got detached from the enemy prefab. This has been fixed. Also, the Enemy_Idle == Enemy_Walk since there wasn't enough room on the sprite sheet for both, so every animation will definitely be used. Thanks for pointing this out.
