### ISSUE TITLE
[CODE] Inconsistent naming

### ISSUE THREAD

**Issue by louisgv** [DanGiaime/IGME119-2DPlatformer#2]
The sceneChanger and playerController components are using lowerCamelCase. However the rest of the project is using UpperCamelCase.

Related: 

https://github.com/DanGiaime/IGME119-2DPlatformer/blob/6933afed0e2b6d61fd64693688ef7c89100217a6/IGME119-2DPlatformer/Assets/Scripts/sceneChanger.cs

https://github.com/DanGiaime/IGME119-2DPlatformer/blob/6933afed0e2b6d61fd64693688ef7c89100217a6/IGME119-2DPlatformer/Assets/Scripts/playerController.cs

**Comment by roxworks** [comment]
Fixed. Thanks for pointing that out.
