### ISSUE TITLE
[BUG] Platformer should not auto-scroll

### ISSUE THREAD

**Issue by louisgv** [DanGiaime/IGME119-2DPlatformer#4]
Normal platformer should not auto-scroll/advance like a side-scroller. Instead, it should only scroll only when the player's x axis exceed certain threshold.

**Comment by roxworks** [comment]
The Player-Based movement Implementation is now complete. If you wish for your game to follow that pattern, please follow the instructions in the readme to do so. Thanks for pointing this out.
