### ISSUE TITLE
[INCONSISTENCY] Input handling

### ISSUE THREAD

**Issue by louisgv** [DanGiaime/IGME119-2DPlatformer#5]
The user input for jump and movement are inconsistent. Jump are handled with only `Input.GetKeyDown(KeyCode.UpArrow)` whereas movement are using `GetAxis` which will have alternative using wasd keys. Please fix by using `Input.GetButtonDown` instead of `GetKeyDown`

**Comment by roxworks** [comment]
Fixed. Thanks for pointing that out.
