### ISSUE TITLE
[BUG] Player will rotate randomly over the Y-axis if flip while jump

### ISSUE THREAD

**Issue by louisgv** [DanGiaime/IGME119-2DPlatformer#6]
![image](https://user-images.githubusercontent.com/6723574/33361468-469ef430-d4a6-11e7-99bf-8fc5bc5bf44f.png)

I suggest instead of use `transform.Rotate`, you should set the transform to the desired rotation. It would be easier to determine the value of the rotation. Mutating the value make it harder to understand what's wrong.

**Comment by roxworks** [comment]
Fixed. Thank you for pointing this out.
