### ISSUE TITLE
[BUG] Jumping animation is not playing correctly

### ISSUE THREAD

**Issue by louisgv** [DanGiaime/IGME119-2DPlatformer#7]
Seems like the animator controller state is not being handled correctly. You might want to use a Trigger for jump instead of a boolean, since after jump is called in one frame, the next frame walk might be called, and they would collide and switch prematurely.

**Comment by roxworks** [comment]
Some animations are more desirable than others to end preemptively. This change has been reflected in a new update. If there still seem to be issues with the new version, please create a new issue detailing those, and they will be handled. Thanks for pointing that out.
