### ISSUE TITLE
[DEPRECATION] Lots of warning message

### ISSUE THREAD

**Issue by louisgv** [DanGiaime/IGME119-2DPlatformer#8]
![image](https://user-images.githubusercontent.com/6723574/33395924-0471921a-d515-11e7-9ef4-78a373301d6e.png)

**Comment by roxworks** [comment]
Some deprecation warnings have been removed. If you see more deprecation warnings, please create another issue with an image of those warnings, and they will be dealt with. Thanks for pointing this out.
